### PR TITLE
we do a little trolling :trollface: 

### PR DESCRIPTION
**Pull request by BrunoGamerGH**

### CODE REVIEW

**Review by AntonUden — APPROVED** [review]

**Comment by AntonUden** [comment]
100 prs, almost 3 years of development. AND YOU MAKE PR 100 JUST TO FIX A SINGLE LETTER TYPO

**Comment by AntonUden** [comment]
this was the part that people where going to talk about after my death how amazing novacore pr 100 was

**Comment by AntonUden** [comment]
but no

**Comment by AntonUden** [comment]
JUST A SINGLE LETTER

**Comment by THEGOLDENPRO** [comment]
UGGHHHHHHHHHH!

**Pull request merged**
